apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.zbialik.io/name: prometheus-autoscale

resources:
- prometheus.yaml
- service.yaml
- ingress.yaml

configurations:
  - kustomizeconfig/prometheus.yaml

configMapGenerator:
  - name: snapshot-upload-python-script
    files:
      - snapshot-upload.py

generatorOptions:
  disableNameSuffixHash: true
