apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-shard-autoscaler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-shard-autoscaler
subjects:
- kind: ServiceAccount
  name: prometheus-shard-autoscaler
  namespace: monitoring
